//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemiNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorMusaitligi
    {
        public int ID { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public Nullable<int> GunID { get; set; }
        public Nullable<int> SaatID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Gunler Gunler { get; set; }
        public virtual Saatler Saatler { get; set; }
        public virtual Users Users { get; set; }
    }
}
