//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemiNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gunler()
        {
            this.DoktorMusaitligi = new HashSet<DoktorMusaitligi>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> Pazartesi { get; set; }
        public Nullable<bool> Sali { get; set; }
        public Nullable<bool> Carsamba { get; set; }
        public Nullable<bool> Persembe { get; set; }
        public Nullable<bool> Cuma { get; set; }
        public Nullable<bool> Cumartesi { get; set; }
        public Nullable<bool> Pazar { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoktorMusaitligi> DoktorMusaitligi { get; set; }
    }
}
