//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemiNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int ID { get; set; }
        public string HastaAd { get; set; }
        public string HastaPhone { get; set; }
        public string HastaMail { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public Nullable<System.DateTime> RandevuTarih { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Users Users { get; set; }
    }
}
